### ISSUE TITLE
Do we have a naming comparison table for functions?

### ISSUE THREAD

**Issue by pomodorozhong** [xinu-os/xinu#32]
I'm learning Xinu using the book ["Operating System Design: The Xinu Approach, Linksys Version"](https://www.oreilly.com/library/view/operating-system-design/9781439881118/) and this repository.

At first, I noticed there is some functions mentioned in the book, that is not in this repo. Then I found out that It's just got renamed. Here is a example:

| Xinu in the book  | Embedded Xinu |
| ----------------- | ------------- |
| getbuf() | bufget() |

And currently I can't find the correspondence to the mkbufpool() in the book.

| Xinu in the book  | Embedded Xinu |
| ----------------- | ------------- |
| mkbufpool() | ? |

Is there any naming comparison table out there? If not, can we have one?

**Comment by brylow** [comment]
I don't believe Dr. Comer shares the book version of his code in any public revision control systems, although there may be tarballs available from his website.  Embedded Xinu evolved in parallel to the version he wrote for the Linksys edition of the text, but the constraints of carefully typesetting code for a textbook aren't usually compatible with an open source project.
I think our name for the function you mention is bfpalloc.  The motif in Embedded Xinu is that related functions are grouped by common prefix, like "bfp" for buffer pool, rather than by primary verb, like in classic 1980's Xinu.
